-- Rode este arquivo no SQL Editor do Supabase.
-- Ele ajusta a tabela para aceitar exatamente os campos do index1.html.

CREATE TABLE IF NOT EXISTS multas (
  id BIGINT PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE multas
ADD COLUMN IF NOT EXISTS linha TEXT,
ADD COLUMN IF NOT EXISTS carro TEXT,
ADD COLUMN IF NOT EXISTS placa TEXT,
ADD COLUMN IF NOT EXISTS data TEXT,
ADD COLUMN IF NOT EXISTS hora TEXT,
ADD COLUMN IF NOT EXISTS local TEXT,
ADD COLUMN IF NOT EXISTS municipio TEXT,
ADD COLUMN IF NOT EXISTS infracao TEXT,
ADD COLUMN IF NOT EXISTS auto TEXT,
ADD COLUMN IF NOT EXISTS motorista TEXT,
ADD COLUMN IF NOT EXISTS valor NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS assinado TEXT,
ADD COLUMN IF NOT EXISTS pago TEXT,
ADD COLUMN IF NOT EXISTS envio_rca TEXT,
ADD COLUMN IF NOT EXISTS prazo_aceite TEXT,
ADD COLUMN IF NOT EXISTS dp TEXT,
ADD COLUMN IF NOT EXISTS status TEXT,
ADD COLUMN IF NOT EXISTS obs TEXT,
ADD COLUMN IF NOT EXISTS data_suspeita BOOLEAN DEFAULT false;

-- Garante que campos que podem receber texto como "OK", "S/N" ou vazio não travem a importação.
ALTER TABLE multas ALTER COLUMN linha TYPE TEXT USING linha::TEXT;
ALTER TABLE multas ALTER COLUMN data TYPE TEXT USING data::TEXT;
ALTER TABLE multas ALTER COLUMN hora TYPE TEXT USING hora::TEXT;
ALTER TABLE multas ALTER COLUMN local TYPE TEXT USING local::TEXT;
ALTER TABLE multas ALTER COLUMN municipio TYPE TEXT USING municipio::TEXT;
ALTER TABLE multas ALTER COLUMN envio_rca TYPE TEXT USING envio_rca::TEXT;
ALTER TABLE multas ALTER COLUMN prazo_aceite TYPE TEXT USING prazo_aceite::TEXT;
ALTER TABLE multas ALTER COLUMN dp TYPE TEXT USING dp::TEXT;
